# Generated by Django 4.1.3 on 2022-12-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_shahida', '0002_alter_blogpost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to='media/featured_image'),
        ),
    ]
