# Generated by Django 4.1.3 on 2023-01-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr_shahida', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
