# Generated by Django 4.1.3 on 2023-01-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dr_shahida', '0010_remove_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='show_on_home',
            field=models.BooleanField(default=True),
        ),
    ]
