# Generated by Django 4.1.3 on 2023-01-17 09:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dr_shahida', '0011_blogpost_show_on_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='status',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
