# Generated by Django 4.1.3 on 2023-01-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dr_shahida', '0012_serialnumber_remove_blogpost_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SerialNumber',
        ),
    ]
